export const FILL_BROADCAST_ACTION: 'FILL_BROADCAST_ACTION' = 'FILL_BROADCAST_ACTION';

export const FETCH_ROOMS_LIST_ACTION: 'FETCH_ROOMS_LIST_ACTION' = 'FETCH_ROOMS_LIST_ACTION';

export const FETCH_ROOM_INFO_ACTION: 'FETCH_ROOM_INFO_ACTION' = 'FETCH_ROOM_INFO_ACTION';

export const FILL_ROOM_ACTION: 'FILL_ROOM_ACTION' = 'FILL_ROOM_ACTION';

export const FILL_PROFILE_ACTION: 'FILL_PROFILE_ACTION' = 'FILL_PROFILE_ACTION';

export const FILL_ACTIVE_ACTION: 'FILL_ACTIVE_ACTION' = 'FILL_ACTIVE_ACTION';

export const FILL_PLAYLIST_ACTION: 'FILL_PLAYLIST_ACTION' = 'FILL_PLAYLIST_ACTION';

export const LOGIN: 'LOGIN' = 'LOGIN';

export const ADD_TO_PLAYLIST: 'ADD_TO_PLAYLIST' = 'ADD_TO_PLAYLIST';

export const GET_PLAYLIST: 'GET_PLAYLIST' = 'GET_PLAYLIST';

export const FETCH_PROFILE_ACTION: 'FETCH_PROFILE_ACTION' = 'FETCH_PROFILE_ACTION';

export const FILL_NOW_PLAYING_ACTION: 'FILL_NOW_PLAYING_ACTION' = 'FILL_NOW_PLAYING_ACTION';

export const FETCH_CURRENT_SONG_DETAILS_ACTION: 'FETCH_CURRENT_SONG_DETAILS_ACTION' =
  'FETCH_CURRENT_SONG_DETAILS_ACTION';
