export const FILL_BROADCAST_ACTION: 'FILL_BROADCAST_ACTION' = 'FILL_BROADCAST_ACTION';

export const FETCH_ROOMS_LIST_ACTION: 'FETCH_ROOMS_LIST_ACTION' = 'FETCH_ROOMS_LIST_ACTION';

export const FETCH_ROOM_INFO_ACTION: 'FETCH_ROOM_INFO_ACTION' = 'FETCH_ROOM_INFO_ACTION';

export const FILL_ROOM_ACTION: 'FILL_ROOM_ACTION' = 'FILL_ROOM_ACTION';

export const FILL_PROFILE_ACTION: 'FILL_PROFILE_ACTION' = 'FILL_PROFILE_ACTION';

export const FILL_ACTIVE_ACTION: 'FILL_ACTIVE_ACTION' = 'FILL_ACTIVE_ACTION';

export const FILL_PLAYLIST_ACTION: 'FILL_PLAYLIST_ACTION' = 'FILL_PLAYLIST_ACTION';

export const LOGIN: 'LOGIN' = 'LOGIN';

export const ADD_TO_PLAYLIST: 'ADD_TO_PLAYLIST' = 'ADD_TO_PLAYLIST';

export const GET_PLAYLIST: 'GET_PLAYLIST' = 'GET_PLAYLIST';

export const FETCH_PROFILE_ACTION: 'FETCH_PROFILE_ACTION' = 'FETCH_PROFILE_ACTION';

export const FILL_NOW_PLAYING_ACTION: 'FILL_NOW_PLAYING_ACTION' = 'FILL_NOW_PLAYING_ACTION';

export const FILL_PLAYER_ACTION: 'FILL_PLAYER_ACTION' = 'FILL_PLAYER_ACTION';

export const FETCH_USERS: 'FETCH_USERS' = 'FETCH_USERS';

export const CREATE_ROOM: 'CREATE_ROOM' = 'CREATE_ROOM';

export const FETCH_CURRENT_SONG_DETAILS_ACTION: 'FETCH_CURRENT_SONG_DETAILS_ACTION' =
  'FETCH_CURRENT_SONG_DETAILS_ACTION';

export const LEAVE_ROOM_ACTION: 'LEAVE_ROOM_ACTION' = 'LEAVE_ROOM_ACTION';

export const REMOVE_FINISHED_SONG: 'REMOVE_FINISHED_SONG' = 'REMOVE_FINISHED_SONG';

export const RESET_NOW_PLAYING_STATE: 'RESET_NOW_PLAYING_STATE' = 'RESET_NOW_PLAYING_STATE';

export const RESET_ROOM_STATE: 'RESET_ROOM_STATE' = 'RESET_ROOM_STATE';

export const RESET_BROADCAST_STATE: 'RESET_BROADCAST_STATE' = 'RESET_BROADCAST_STATE';
