export const FILL_BROADCAST_ACTION: 'FILL_BROADCAST_ACTION' = 'FILL_BROADCAST_ACTION';

export const FILL_ROOM_ACTION: 'FILL_ROOM_ACTION' = 'FILL_ROOM_ACTION';

export const FILL_PROFILE_ACTION: 'FILL_PROFILE_ACTION' = 'FILL_PROFILE_ACTION';

export const FILL_ACTIVE_ACTION: 'FILL_ACTIVE_ACTION' = 'FILL_ACTIVE_ACTION';
