export const BROADCAST_SONG_TIMESTAMP: 'BROADCAST_SONG_TIMESTAMP' = 'BROADCAST_SONG_TIMESTAMP';

export const UPDATE_NOW_PLAYING: 'UPDATE_NOW_PLAYING' = 'UPDATE_NOW_PLAYING';

export const BROADCAST_MASTER_SELECTION_REQUEST: 'BROADCAST_MASTER_SELECTION_REQUEST' =
  'BROADCAST_MASTER_SELECTION_REQUEST';

export const REQUEST_TO_BE_MASTER: 'REQUEST_TO_BE_MASTER' = 'REQUEST_TO_BE_MASTER';

export const CHECK_MASTER_IS_ONLINE: 'CHECK_MASTER_IS_ONLINE' = 'CHECK_MASTER_IS_ONLINE';

export const ACK_MASTER_IS_ONLINE: 'ACK_MASTER_IS_ONLINE' = 'ACK_MASTER_IS_ONLINE';

export const UPDATE_ROOM_DETAILS: 'UPDATE_ROOM_DETAILS' = 'UPDATE_ROOM_DETAILS';
